/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_rdh_compsci_util_ConsoleUtils */

#ifndef _Included_dev_rdh_compsci_util_ConsoleUtils
#define _Included_dev_rdh_compsci_util_ConsoleUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef dev_rdh_compsci_util_ConsoleUtils_BOLD
#define dev_rdh_compsci_util_ConsoleUtils_BOLD 1L
#undef dev_rdh_compsci_util_ConsoleUtils_FAINT
#define dev_rdh_compsci_util_ConsoleUtils_FAINT 2L
#undef dev_rdh_compsci_util_ConsoleUtils_ITALIC
#define dev_rdh_compsci_util_ConsoleUtils_ITALIC 3L
#undef dev_rdh_compsci_util_ConsoleUtils_UNDERLINE
#define dev_rdh_compsci_util_ConsoleUtils_UNDERLINE 4L
#undef dev_rdh_compsci_util_ConsoleUtils_STRIKETHROUGH
#define dev_rdh_compsci_util_ConsoleUtils_STRIKETHROUGH 9L
#undef dev_rdh_compsci_util_ConsoleUtils_DOUBLE_UNDERLINE
#define dev_rdh_compsci_util_ConsoleUtils_DOUBLE_UNDERLINE 21L
#undef dev_rdh_compsci_util_ConsoleUtils_BLACK
#define dev_rdh_compsci_util_ConsoleUtils_BLACK 30L
#undef dev_rdh_compsci_util_ConsoleUtils_RED
#define dev_rdh_compsci_util_ConsoleUtils_RED 31L
#undef dev_rdh_compsci_util_ConsoleUtils_GREEN
#define dev_rdh_compsci_util_ConsoleUtils_GREEN 32L
#undef dev_rdh_compsci_util_ConsoleUtils_YELLOW
#define dev_rdh_compsci_util_ConsoleUtils_YELLOW 33L
#undef dev_rdh_compsci_util_ConsoleUtils_BLUE
#define dev_rdh_compsci_util_ConsoleUtils_BLUE 34L
#undef dev_rdh_compsci_util_ConsoleUtils_MAGENTA
#define dev_rdh_compsci_util_ConsoleUtils_MAGENTA 35L
#undef dev_rdh_compsci_util_ConsoleUtils_CYAN
#define dev_rdh_compsci_util_ConsoleUtils_CYAN 36L
#undef dev_rdh_compsci_util_ConsoleUtils_WHITE
#define dev_rdh_compsci_util_ConsoleUtils_WHITE 37L
/*
 * Class:     dev_rdh_compsci_util_ConsoleUtils
 * Method:    terminalWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_rdh_compsci_util_ConsoleUtils_terminalWidth
  (JNIEnv *, jclass);

/*
 * Class:     dev_rdh_compsci_util_ConsoleUtils
 * Method:    terminalHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_rdh_compsci_util_ConsoleUtils_terminalHeight
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
